services:
  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./nginx/conf/192.168.1.204.crt:/etc/nginx/conf.d/192.168.1.204.crt:ro
      - ./nginx/conf/192.168.1.204.key:/etc/nginx/conf.d/192.168.1.204.key:ro
